### ISSUE TITLE
"./gradlew build run" not working because gradle wrapper is missing in the project

### ISSUE THREAD

**Issue by aruld** [firebase/quickstart-java#1]
you can run this command to generate a gradle wrapper and add the wrapper to the project
`gradle wrapper`

**Comment by samtstern** [comment]
@aruld `gradlew` is provided in the `database` folder.  The instructions assume you are running commands from that folder.   It should be working for you if you do that.

https://github.com/firebase/quickstart-java/blob/master/database/gradlew

**Comment by aruld** [comment]
@samtstern The problem is https://github.com/firebase/quickstart-java/tree/master/database/gradle/wrapper does not have the wrapper: gradle-wrapper.jar. This is referenced in gradlew (CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar). So, it does not run out of the box, you need to add this jar to this folder.

**Comment by samtstern** [comment]
@aruld thanks for catching that!  Sorry I closed the issue prematurely.  It should be fixed now, was a gitignore issue.

**Comment by aruld** [comment]
@samtstern sure, np! Thank you for patching that.
