### ISSUE TITLE
Please Help Me 

### ISSUE THREAD

**Issue by tango4567** [firebase/quickstart-java#24]
I know this is not the right place to ask that kind to question here but I am not able to get more documentation on the following issue.
**Question 1**  .setCredentials() and Error:(33, 20) Failed to resolve: com.google.firebase:firebase-admin:11.8.0

FileInputStream serviceAccount = null;
        try {
            serviceAccount = new FileInputStream("path/to/serviceAccountKey.json");
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
        FirebaseOptions options = new FirebaseOptions.Builder()
                **.setCredentials(GoogleCredentials.fromStream(serviceAccount))**
                .setDatabaseUrl("https://example.firebaseio.com/")
                .build();
        **FirebaseApp.initializeApp(options);**

Not able to find solution and documentation for this. After reading multiple instructions and documentation I found these following data 

- public FirebaseOptions build ()
- public FirebaseOptions.Builder setApiKey (String apiKey)
- public FirebaseOptions.Builder setApplicationId (String applicationId)
- public FirebaseOptions.Builder setDatabaseUrl (String databaseUrl)
- public FirebaseOptions.Builder setGcmSenderId (String gcmSenderId)
- public FirebaseOptions.Builder setProjectId (String projectId)
- public FirebaseOptions.Builder setStorageBucket (String storageBucket)

**Comment by samtstern** [comment]
@tango4567 the "failed to resolve" error message sounds like an issue with your Maven or Gradle configuration.  Please ask this question on StackOverflow and someone can help you debug.
