### ISSUE TITLE
Update Gradle Wrapper v3.3

### ISSUE THREAD

**Issue by vagifzeynalov** [firebase/quickstart-java#29]
Hello!

This project uses a very old Gradle Wrapper version 3.3. Check the file `quickstart-java/gradle/wrapper/gradle-wrapper.properties`

```
#Mon Jun 05 12:42:45 PDT 2017
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-3.3-all.zip
```

And it leads to the error
```
Unable to start the daemon process.
The project uses Gradle 3.3 which is incompatible with Java 11 or newer.

Possible solution:
 - Upgrade Gradle wrapper to 4.8.1 version and re-import the project
 - Use Java 8 as Gradle JVM: Open Gradle settings 
```

Could you please to update it to the most recent one?

Thank you,
Vagif

**Comment by samtstern** [comment]
@vagifzeynalov would you be interested in sending a Pull Request?

**Comment by vagifzeynalov** [comment]
Hi @samedson ,
Sure, I can do it!

Thanks for quick response,
Vagif

**Comment by vagifzeynalov** [comment]
PR has been created https://github.com/firebase/quickstart-java/pull/30
