### ISSUE TITLE
Authentication failed: invalid_token

### ISSUE THREAD

**Issue by winstonma** [firebase/quickstart-java#3]
I created a Firebase project and downloaded this repo, created service-account.json.

In addition in the Database.java I added some sample code from the [Firebase QuickStart Guide - Save Data](https://firebase.google.com/docs/database/server/save-data) to store some data. However I got the following error
`[WARN] PersistentConnection: pc_0 - Authentication failed: invalid_token (Access denied.)
`

Here is my database rules.
```
{
  "rules": {
    ".read": true,
    ".write": true
  }
}
```
It should allows any read/write.

I have no idea how to get the auth done. Thanks for the help

**Comment by winstonma** [comment]
Seem using firebase-server-sdk 3.0.1 solve the problem

**Comment by winstonma** [comment]
Is it possible to update the SDK in the sample?

Thanks

**Comment by samtstern** [comment]
@winstonma done!

**Comment by winstonma** [comment]
Thanks

This is the solution I found in [Stackoverflow](http://stackoverflow.com/questions/37427128/google-firebase-server-persistent-connection-invalid-token)

Although your sample code have no problem. Some people (like me) would use your code a base reference and expand. It would be great if any other developer didn't face the same problem and spend time searching stackoverflow.

**Comment by samtstern** [comment]
@winstonma totally agree, this one is my fault for not upgrading the sample dependency version as soon as `3.0.1` was released.
