### ISSUE TITLE
PersistentConnection: pc_0 - Auth token revoked: expired_token (Auth token is expired.)

### ISSUE THREAD

**Issue by edgesoft** [firebase/quickstart-java#5]
When the server has been up and running for a while I get this. How can I make the token not expire?

**Comment by samtstern** [comment]
@edgesoft how are you getting the token?  Does the SDK recover from this and get itself a new token?

**Comment by edgesoft** [comment]
@samtstern 
```java
final File resource = new File(serviceAccountFile);
FirebaseOptions options = new FirebaseOptions.Builder()
.setServiceAccount(new FileInputStream(resource))
.setDatabaseUrl(database)
.build();
FirebaseApp.initializeApp(options);
DatabaseReference ref = FirebaseDatabase.getInstance().getReference(getCompletedTaskPath());
```

**Comment by edgesoft** [comment]
@samtstern It does not recover

**Comment by mikelehen** [comment]
This is log message is actually expected / benign and the SDK should recover.  When you say it does not recover, can you elaborate on what exactly stops working?

**Comment by edgesoft** [comment]
@mikelehen Yes, you are right. Wrong of me. Thanks!
